name: 'Setup Roswell'
description: 'Install Roswell (Common Lisp environment setup utility) and optionally a specific SBCL version'
author: 'macnod'

inputs:
  sbcl-version:
    description: 'The version of SBCL to install (e.g., 2.5.10). If not specified, the default SBCL will be installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Cache Roswell and SBCL
      uses: actions/cache@v4
      id: cache
      with:
        path: ~/.roswell
        key: roswell-${{ runner.os }}-${{ inputs.sbcl-version || 'default' }}
        restore-keys: |
          roswell-${{ runner.os }}-

    - name: Fix Roswell PATH (cache restore)
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "~/.roswell exists: $(ls -la ~/.roswell 2>/dev/null || echo 'missing')"
        if [[ -f ~/.roswell/bin/ros ]]; then
          echo "~/.roswell/bin already in PATH"
        else
          echo "Fixing PATH for restored cache..."
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
          echo "PATH updated:"
          echo $PATH
        fi

    - name: Install Roswell
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Installing Roswell (no cache hit)"
        curl -L https://github.com/roswell/roswell/releases/download/v23.10.14.114/roswell_23.10.14.114-1_amd64.deb -o roswell.deb
        sudo dpkg -i roswell.deb
        echo "$HOME/.roswell/bin" >> $GITHUB_PATH

    - name: Install SBCL
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Installing SBCL ${{ inputs.sbcl-version || '2.5.10' }} (no cache hit)"
        ros install sbcl-bin/${{ inputs.sbcl-version || '2.5.10' }}
        ros use sbcl-bin/${{ inputs.sbcl-version || '2.5.10' }}

    - name: Verify Installation
      shell: bash
      run: |
        set -e
        echo "✅ Cache hit: ${{ steps.cache.outputs.cache-hit }}"
        echo "PATH includes .roswell/bin: $(echo $PATH | tr ':' '\n' | grep roswell)"
        which ros || echo "ros not in PATH"
        echo "Roswell version:"
        ros version
        echo "SBCL version:"
        ros run -- --version

branding:
  icon: 'package'
  color: 'blue'
