name: 'Setup Roswell'
description: 'Install Roswell (Common Lisp environment setup utility) and optionally a specific SBCL version'
author: 'macnod'

inputs:
  roswell-version:
    description: 'Roswell version. Default: 23.10.14.114'
    required: false
    default: '23.10.14.114'
  sbcl-version:
    description: 'SBCL version. Default: 2.5.10'
    required: false
    default: '2.5.10'

runs:
  using: 'composite'
  steps:
    - name: Install Roswell (system-wide)
      shell: bash
      run: |
        url_prefix="https://github.com/roswell/roswell/releases/download"
        roswell_version="${{ inputs.roswell-version }}"
        url="${url_prefix}/v${roswell_version}/roswell_${roswell_version}-1_amd64.deb"
        echo "Installing Roswell..."
        curl -fsSL "${url}" -o roswell.deb || { echo "Failed to download Roswell $roswell_version"; exit 1; }
        sudo dpkg -i roswell.deb
        echo "ros path: $(which ros)"
        dpkg-query -L roswell
        rm roswell.deb

    - name: Setup SBCL
      shell: bash
      run: |
        sbcl_version="${{ inputs.sbcl-version }}"
        echo "Installing SBCL $sbcl_version (no cache)"
        ros install sbcl-bin/$sbcl_version
        ros use sbcl-bin/$sbcl_version

    - name: Verify Installation
      shell: bash
      run: |
        set -e
        echo "Roswell version:"
        ros version
        echo "Active SBCL:"
        ros run -- --version
        echo "Installed impls:"
        ros list installed | grep sbcl

branding:
  icon: 'package'
  color: 'blue'
