name: 'Setup Roswell'
description: 'Install Roswell (Common Lisp environment setup utility) and optionally a specific SBCL version'
author: 'macnod'

inputs:
  sbcl-version:
    description: 'The version of SBCL to install (e.g., 2.5.10). If not specified, the default SBCL will be installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Roswell
      shell: bash
      run: |
        set -e
        echo "Installing Roswell..."
        curl -sSL https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
        
    - name: Add Roswell to PATH
      shell: bash
      run: |
        echo "$HOME/.roswell/bin" >> $GITHUB_PATH
        echo "/usr/local/bin" >> $GITHUB_PATH
        
    - name: Install SBCL
      shell: bash
      run: |
        set -e
        if [ -n "${{ inputs.sbcl-version }}" ]; then
          echo "Installing SBCL version ${{ inputs.sbcl-version }}..."
          ros install sbcl/${{ inputs.sbcl-version }}
          ros use sbcl/${{ inputs.sbcl-version }}
        else
          echo "Installing default SBCL..."
          ros install sbcl-bin
        fi
        
    - name: Verify Installation
      shell: bash
      run: |
        set -e
        echo "Roswell version:"
        ros version
        echo ""
        echo "SBCL version:"
        ros run -- --version

branding:
  icon: 'package'
  color: 'blue'
