name: 'Setup Roswell'
description: 'Install Roswell (Common Lisp environment setup utility) and optionally a specific SBCL version'
author: 'macnod'

inputs:
  sbcl-version:
    description: 'The version of SBCL to install (e.g., 2.5.10). If not specified, the default SBCL will be installed.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Cache Roswell and SBCL
      id: cache
      shell: bash
      run: |
        cache_key="roswell-${{ inputs.sbcl-version || 'default' }}"
        echo "cache-hit=false" >> $GITHUB_OUTPUT
        if [[ -d "$HOME/.roswell" ]]; then
          echo "cache-hit=true" >> $GITHUB_OUTPUT
          echo "Roswell cache hit!"
        fi

    - name: Install Roswell
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -L https://github.com/roswell/roswell/releases/download/v23.10.14.114/roswell_23.10.14.114-1_amd64.deb -o roswell.deb
        sudo dpkg -i roswell.deb

    - name: Install SBCL
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        ros install sbcl-bin/${{ inputs.sbcl-version || '2.5.10' }}
        ros use sbcl-bin/${{ inputs.sbcl-version || '2.5.10' }}

    - name: Verify Installation
      shell: bash
      run: |
        set -e
        echo "Roswell version:"
        ros version
        echo ""
        echo "SBCL version:"
        ros run -- --version

branding:
  icon: 'package'
  color: 'blue'
