name: 'Setup Roswell'
description: 'Install Roswell (Common Lisp environment setup utility) and optionally a specific SBCL version'
author: 'macnod'

inputs:
  roswell-version:
    description: 'Roswell version. Default: 23.10.14.114'
    required: false
    default: '23.10.14.114'
  sbcl-version:
    description: 'SBCL version. Default: 2.5.10'
    required: false
    default: '2.5.10'
  disable-cache:
    description: 'Disable caching'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Debug caching
      shell: bash
      run: |
        echo "disable-cache: '${{inputs.disable-cache}}'"

    - name: Bogus
      shell: bash
      run: |
        echo "Bogus step"

    - name: Cache disabled
      if: inputs.disable-cache == 'false'
      shell: bash
      run: |
        echo "Cache enabled"

    - name: Cache enabled
      if: inputs.disable-cache == 'true'
      shell: bash
      run: |
        echo "Cache disabled"

    - name: Cache full Roswell
      uses: actions/cache@v4
      id: cache
      with:
        path: ~/.roswell
        key: roswell-${{ runner.os }}-${{ inputs.roswell-version }}-${{ inputs.sbcl-version }}
        restore-keys: |
          roswell-${{ runner.os }}-

    - name: Install Roswell (system-wide)
      if: inputs.disable-cache == 'true' || steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        url_prefix="https://github.com/roswell/roswell/releases/download"
        roswell_version="${{ inputs.roswell-version }}"
        url="${url_prefix}/v${roswell_version}/roswell_${roswell_version}-1_amd64.deb"
        echo "Installing Roswell..."
        curl -fsSL "${url}" -o roswell.deb || { echo "Failed to download Roswell $roswell_version"; exit 1; }
        sudo dpkg -i roswell.deb
        rm roswell.deb

    - name: Roswell already installed
      if: inputs.disable-cache == 'false' && steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "✅ Cache hit. Roswell installed from cache"

    - name: Setup SBCL (cache miss or ensure active)
      if: inputs.disable-cache == 'true' || steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sbcl_version="${{ inputs.sbcl-version }}"
        echo "Installing SBCL $sbcl_version (no cache)"
        ros install sbcl-bin/$sbcl_version
        ros use sbcl-bin/$sbcl_version

    - name: Activate cached SBCL
      if: steps.cache.outputs.cache-hit == 'true' && inputs.disable-cache == 'false'
      shell: bash
      run: |
        sbcl_version="${{ inputs.sbcl-version }}"
        echo "Activating cached SBCL $sbcl_version"
        ros use sbcl-bin/$sbcl_version

    - name: Verify Installation
      shell: bash
      run: |
        set -e
        echo "✅ Cache hit: ${{ steps.cache.outputs.cache-hit }}"
        echo "✅ Disable cache: ${{ inputs.disable-cache }}"
        echo "Roswell version:"
        ros version
        echo "Active SBCL:"
        ros run -- --version
        echo "Installed impls:"
        ros list installed | grep sbcl

branding:
  icon: 'package'
  color: 'blue'
